name: cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.13.0
        with:
          java-version: "21"
          java-distribution: "temurin"
          maven-version: "3.9.6"

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>codeartifact</id>
                      <username>aws</username>
                      <password>${{ secrets.CODEARTIFACT_AUTH_TOKEN }}</password>
                    </server>
                  </servers>
                  <mirrors>
                    <mirror>
                      <id>codeartifact</id>
                      <mirrorOf>*</mirrorOf>
                      <url>https://${{ secrets.DOMAIN }}-${{ secrets.OWNER }}.d.codeartifact.eu-west-3.amazonaws.com/maven/${{ secrets.REPO_NAME }}/</url>
                    </mirror>
                  </mirrors>
                </settings>" > ~/.m2/settings.xml

      - name: Publish package to AWS CodeArtifact
        run: mvn deploy --settings ~/.m2/settings.xml